# --- C++ E LIBRERIE STANDARD ---
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_NEWLIB_LIBC=y

# --- PERIFERICHE ---
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# --- TENSORFLOW ---
CONFIG_FPU=y
CONFIG_TENSORFLOW_LITE_MICRO=y

# --- OTTIMIZZAZIONI VELOCITA' ---
# Diciamo a Zephyr di compilare il C++ per la MASSIMA velocità!
CONFIG_SPEED_OPTIMIZATIONS=y

# Spegniamo il debug perché azzera la velocità dell'IA
CONFIG_DEBUG=n
CONFIG_LOG=n
CONFIG_ASSERT=n